apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
  name: rag-query-backend
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '100'
        run.googleapis.com/client-name: cloud-console
        run.googleapis.com/startup-cpu-boost: 'true'
      labels:
        run.googleapis.com/startupProbeType: Default
    spec:
      containerConcurrency: 80
      containers:
      - env:
        - name: WEAVIATE_URL
          value: https://ds4tx7ttr3ciaui5obmowg.c0.us-east1.gcp.weaviate.cloud
        - name: GOOGLE_CLOUD_PROJECT
          value: jkwng-vertex-playground
        - name: GOOGLE_CLOUD_REGION
          value: us-central1
        image: gcr.io/jkwng-images/rag-query-backend
        name: rag-query-1
        ports:
        - containerPort: 8000
          name: http1
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
        startupProbe:
          failureThreshold: 1
          periodSeconds: 240
          tcpSocket:
            port: 8000
          timeoutSeconds: 240
      serviceAccountName: 205512073711-compute@developer.gserviceaccount.com
      timeoutSeconds: 300
  traffic:
  - latestRevision: true
    percent: 100
